### Editando dataset Sales

In [1]:
# Importando bibliotecas

import pandas as pd
import numpy as np

In [2]:
# importando tabela

base_vendas = pd.read_csv("online_sales_dataset.csv")
base_vendas

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00,70.92,51445.0,Spain,0.200000,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00,51.74,28879.0,United States,0.230000,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00,85.25,21825.0,Portugal,0.200000,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00,39.64,43199.0,United Kingdom,0.310000,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00,38.27,53328.0,France,0.100000,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low

In [3]:
# excluindo valores negativos da coluna "Quantity"

base_vendas = base_vendas[base_vendas['Quantity'] >= 0]
#base_vendas = base_vendas[base_vendas['InvoiceDate'] <= 2024-31-10]
base_vendas

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.47,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.19,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.14,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
5,744167,SKU_1006,Office Chair,47,2020-01-01 05:00,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00,70.92,51445.0,Spain,0.20,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00,51.74,28879.0,United States,0.23,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00,85.25,21825.0,Portugal,0.20,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00,39.64,43199.0,United Kingdom,0.31,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00,38.27,53328.0,France,0.10,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low

In [4]:
# Supondo que 'InvoiceDate' esteja no formato datetime
base_vendas['InvoiceDate'] = pd.to_datetime(base_vendas['InvoiceDate'])

<ipython-input-4-90ebcaa641f7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_vendas['InvoiceDate'] = pd.to_datetime(base_vendas['InvoiceDate'])

In [5]:
# Filtrar as datas atÃ© 31/10/2024
base_vendas = base_vendas[base_vendas['InvoiceDate'] <= '2024-10-31']

base_vendas

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00:00,1.71,37039.0,Australia,0.47,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00:00,41.25,19144.0,Spain,0.19,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00:00,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00:00,76.68,96586.0,Netherlands,0.14,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
5,744167,SKU_1006,Office Chair,47,2020-01-01 05:00:00,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42356,107420,SKU_1885,Blue Pen,25,2024-10-30 20:00:00,48.17,35985.0,United Kingdom,0.20,paypall,9.47,Furniture,Online,Not Returned,FedEx,Paris,Medium
42357,793881,SKU_1003,Headphones,49,2024-10-30 21:00:00,61.50,86466.0,Australia,0.10,Bank Transfer,17.04,Apparel,In-store,Returned,DHL,Rome,Low
42358,355023,SKU_1563,Backpack,10,2024-10-30 22:00:00,37.85,70406.0,Netherlands,0.23,Credit Card,9.23,Apparel,In-store,Not Returned,UPS,Amsterdam,Low
42359,869208,SKU_1366,Office Chair,36,2024-10-30 23:00:00,70.46,66420.0,Spain,0.03,Credit Card,25.54,Stationery,Online,Not Returned,FedEx,Paris,Medium
42360,909450,SKU_1006,T-shirt,15,2024-10-31 00:00:00,92.92,97960.0,Germany,0.19,paypall,7.39,Apparel,In-store,Not Returned,Royal Mail,Rome,Medium

In [6]:
base_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40290 entries, 0 to 42360
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   InvoiceNo          40290 non-null  int64
 1   StockCode          40290 non-null  object
 2   Description        40290 non-null  object
 3   Quantity           40290 non-null  int64
 4   InvoiceDate        40290 non-null  datetime64[ns]
 5   UnitPrice          40290 non-null  float64
 6   CustomerID         38163 non-null  float64
 7   Country            40290 non-null  object
 8   Discount           40290 non-null  float64
 9   PaymentMethod      40290 non-null  object
 10  ShippingCost       40290 non-null  float64
 11  Category           40290 non-null  object
 12  SalesChannel       40290 non-null  object
 13  ReturnStatus       40290 non-null  object
 14  ShipmentProvider   40290 non-null  object
 15  WarehouseLocation  39424 non-null  object
 16  OrderPriority      40290 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(2), object(10)
memory usage: 5.5+ MB

In [7]:
print(base_vendas.shape)

(40290, 17)

In [8]:
print(base_vendas.isnull().sum())

InvoiceNo               0
StockCode               0
Description             0
Quantity                0
InvoiceDate             0
UnitPrice               0
CustomerID           2127
Country                 0
Discount                0
PaymentMethod           0
ShippingCost            0
Category                0
SalesChannel            0
ReturnStatus            0
ShipmentProvider        0
WarehouseLocation     866
OrderPriority           0
dtype: int64

In [9]:
# Excluindo linhas vazias

base_vendas = base_vendas.dropna()

print(base_vendas.shape)
print(base_vendas.isnull().sum())

(38163, 17)
InvoiceNo            0
StockCode            0
Description          0
Quantity             0
InvoiceDate          0
UnitPrice            0
CustomerID           0
Country              0
Discount             0
PaymentMethod        0
ShippingCost         0
Category             0
SalesChannel         0
ReturnStatus         0
ShipmentProvider     0
WarehouseLocation    0
OrderPriority        0
dtype: int64

In [10]:
base_vendas

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00:00,1.71,37039.0,Australia,0.47,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00:00,41.25,19144.0,Spain,0.19,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00:00,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00:00,76.68,96586.0,Netherlands,0.14,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
5,744167,SKU_1006,Office Chair,47,2020-01-01 05:00:00,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Electronics,Online,Not Returned,DHL,London,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42356,107420,SKU_1885,Blue Pen,25,2024-10-30 20:00:00,48.17,35985.0,United Kingdom,0.20,paypall,9.47,Furniture,Online,Not Returned,FedEx,Paris,Medium
42357,793881,SKU_1003,Headphones,49,2024-10-30 21:00:00,61.50,86466.0,Australia,0.10,Bank Transfer,17.04,Apparel,In-store,Returned,DHL,Rome,Low
42358,355023,SKU_1563,Backpack,10,2024-10-30 22:00:00,37.85,70406.0,Netherlands,0.23,Credit Card,9.23,Apparel,In-store,Not Returned,UPS,Amsterdam,Low
42359,869208,SKU_1366,Office Chair,36,2024-10-30 23:00:00,70.46,66420.0,Spain,0.03,Credit Card,25.54,Stationery,Online,Not Returned,FedEx,Paris,Medium
42360,909450,SKU_1006,T-shirt,15,2024-10-31 00:00:00,92.92,97960.0,Germany,0.19,paypall,7.39,Apparel,In-store,Not Returned,Royal Mail,Rome,Medium

#### Analisando produtos e categorias

* AnÃ¡lise dos produtos e categorias para verificar se os produtos estÃ£o classificados corretamente.

In [11]:
# Selecionando as categorias 'Description' e 'Category'

prod_cat = base_vendas[['Description', 'Category']]
prod_cat.head(20)

       Description     Category
0        White Mug      Apparel
1        White Mug  Electronics
2       Headphones  Electronics
3        Desk Lamp  Accessories
5     Office Chair  Electronics
6        USB Cable   Stationery
7         Notebook  Electronics
8   Wireless Mouse      Apparel
9       Headphones      Apparel
10        Notebook   Stationery
11    Office Chair    Furniture
12        Blue Pen  Electronics
13      Headphones   Stationery
14      Wall Clock  Electronics
15         T-shirt    Furniture
16    Office Chair      Apparel
17      Headphones   Stationery
18        Backpack  Accessories
19       USB Cable    Furniture
20      Wall Clock  Accessories

###  Os produtos devem ser classificados da seguinte maneira:

Furniture: Office Chair, Desk Lamp

Stationery: Blue Pen, Notebook

Accessories: Backpack, White Mug, Wall Clock, Desk Lamp

Apparel: T-shirt

Electronics: Wireless Mouse, USB Cable, Headphones

* Conforme a tabela acima, percebe-se que hÃ¡ produtos classificados erroneamente, como exemplo, 'White Mug' (canceca branca) classificado como 'Apparel' (vestuÃ¡rio) e tambÃ©m classificado como "Eletronics".

In [12]:
# DicionÃ¡rio com os produtos categorizados corretamente

Category = {
    'T-shirt': 'Apparel',
    'Notebook': 'Stationery',
    'Wireless Mouse': 'Electronics',
    'USB Cable': 'Accessories',
    'Backpack': 'Accessories',
    'Wall Clock': 'Accessories',
    'Blue Pen': 'Stationery',
    'Office Chair': 'Furniture',
    'Desk Lamp': 'Accessories',
    'White Mug': 'Accessories',
    'Headphones': 'Electronics'
}

In [13]:
# Aplicar a correÃ§Ã£o no DataFrame

base_vendas['Category'] = base_vendas['Description'].map(Category)
base_vendas

<ipython-input-13-b90350bcd807>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base_vendas['Category'] = base_vendas['Description'].map(Category)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00:00,1.71,37039.0,Australia,0.47,Bank Transfer,10.79,Accessories,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00:00,41.25,19144.0,Spain,0.19,paypall,9.51,Accessories,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00:00,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00:00,76.68,96586.0,Netherlands,0.14,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
5,744167,SKU_1006,Office Chair,47,2020-01-01 05:00:00,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Furniture,Online,Not Returned,DHL,London,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42356,107420,SKU_1885,Blue Pen,25,2024-10-30 20:00:00,48.17,35985.0,United Kingdom,0.20,paypall,9.47,Stationery,Online,Not Returned,FedEx,Paris,Medium
42357,793881,SKU_1003,Headphones,49,2024-10-30 21:00:00,61.50,86466.0,Australia,0.10,Bank Transfer,17.04,Electronics,In-store,Returned,DHL,Rome,Low
42358,355023,SKU_1563,Backpack,10,2024-10-30 22:00:00,37.85,70406.0,Netherlands,0.23,Credit Card,9.23,Accessories,In-store,Not Returned,UPS,Amsterdam,Low
42359,869208,SKU_1366,Office Chair,36,2024-10-30 23:00:00,70.46,66420.0,Spain,0.03,Credit Card,25.54,Furniture,Online,Not Returned,FedEx,Paris,Medium
42360,909450,SKU_1006,T-shirt,15,2024-10-31 00:00:00,92.92,97960.0,Germany,0.19,paypall,7.39,Apparel,In-store,Not Returned,Royal Mail,Rome,Medium

In [14]:
base_vendas.groupby(["Category","Description"]).size()
base_vendas

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00:00,1.71,37039.0,Australia,0.47,Bank Transfer,10.79,Accessories,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00:00,41.25,19144.0,Spain,0.19,paypall,9.51,Accessories,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00:00,29.11,50472.0,Germany,0.35,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00:00,76.68,96586.0,Netherlands,0.14,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
5,744167,SKU_1006,Office Chair,47,2020-01-01 05:00:00,70.16,53887.0,Sweden,0.48,Credit Card,13.98,Furniture,Online,Not Returned,DHL,London,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42356,107420,SKU_1885,Blue Pen,25,2024-10-30 20:00:00,48.17,35985.0,United Kingdom,0.20,paypall,9.47,Stationery,Online,Not Returned,FedEx,Paris,Medium
42357,793881,SKU_1003,Headphones,49,2024-10-30 21:00:00,61.50,86466.0,Australia,0.10,Bank Transfer,17.04,Electronics,In-store,Returned,DHL,Rome,Low
42358,355023,SKU_1563,Backpack,10,2024-10-30 22:00:00,37.85,70406.0,Netherlands,0.23,Credit Card,9.23,Accessories,In-store,Not Returned,UPS,Amsterdam,Low
42359,869208,SKU_1366,Office Chair,36,2024-10-30 23:00:00,70.46,66420.0,Spain,0.03,Credit Card,25.54,Furniture,Online,Not Returned,FedEx,Paris,Medium
42360,909450,SKU_1006,T-shirt,15,2024-10-31 00:00:00,92.92,97960.0,Germany,0.19,paypall,7.39,Apparel,In-store,Not Returned,Royal Mail,Rome,Medium

In [15]:
# Salvar o DataFrame em um arquivo CSV
base_vendas.to_csv('Sales_novo.csv', index=False)